In [1]:
import pandas as pd
import numpy as np

In [2]:
uf= pd.read_csv("../input/train/user_features.csv")

In [3]:
uf.head()

   node_id  f1  f2  f3  f4  f5  f6  f7  f8  f9  f10  f11  f12  f13
0        2  14  14  14  12  12  12   7   7   7    0    0    0   15
1        3  31   9   7  31  16  12  31  15  12   31   15   12    8
2        4   0   0   0   0   0   0   0   0   0    0    0    0    7
3        5  31   4   1  31   7   1  31   9   1   31    9    0   15
4        6  31  27  20  31  24  14  31  20  10   31   20    5    7

In [4]:
# uf_mat= uf.set_index('node_id').T.to_dict('list')

In [5]:
ulta= uf.T

In [6]:
ulta.columns= ulta.iloc[0]

In [7]:
ulta.reindex(ulta.index.drop('node_id'))

node_id  2        3        4         ...     8874624  8874625  8874626
f1            14       31        0   ...           2       31        8
f2            14        9        0   ...           2       18        2
f3            14        7        0   ...           1        0        0
f4            12       31        0   ...           2       31       15
f5            12       16        0   ...           2       16        4
f6            12       12        0   ...           1        0        0
f7             7       31        0   ...           0       31       21
f8             7       15        0   ...           0       18        4
f9             7       12        0   ...           0        0        0
f10            0       31        0   ...           0       31       28
f11            0       15        0   ...           0       18        8
f12            0       12        0   ...           0        0        0
f13           15        8        7   ...          15       15       15

[13 rows x 8264276 columns]

In [8]:
final_df = pd.read_csv("../input/test/test.csv")

In [9]:
# data.head()

In [10]:
# data['is_chat'].value_counts()

In [11]:
# nw_df= data.loc[data['is_chat']==0]

In [12]:
# nw_df=nw_df.sample(frac=.07)

In [13]:
# final_df= pd.concat([data.loc[data['is_chat']==1], nw_df], ignore_index=True)

In [14]:
final_df.head()

   id  node1_id  node2_id
0   1   7107094   8010772
1   2   7995251   2805801
2   3   2804693   8059549
3   4   4812472   7332370
4   5   5009985   4511909

In [15]:
# del data 
del uf

In [16]:
# final_df['is_chat'].value_counts('0')

In [17]:
np.array(ulta[2].values[1:])

array([14, 14, 14, 12, 12, 12,  7,  7,  7,  0,  0,  0, 15])

In [18]:
final_df['node1']= final_df['node1_id'].apply(lambda x: ulta[x].values[1:] )

In [19]:
type(final_df['node1'][0][0])

numpy.int64

In [20]:
final_df['node2']= final_df["node2_id"].apply(lambda x: ulta[x].values[1:])

In [21]:
final_df.head()

   id                        ...                                                                    node2
0   1                        ...                         [31, 24, 2, 31, 24, 3, 31, 25, 3, 31, 26, 4, 15]
1   2                        ...                                  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7]
2   3                        ...                                 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 15]
3   4                        ...                                 [0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 15]
4   5                        ...                                  [0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 7]

[5 rows x 5 columns]

In [22]:
final_df.to_csv("test_merged_uf.csv", sep=",", index=False)

In [23]:
# mat= data.iloc[:,3:5].values